---

name: Build dockers

on:
  push:
    branches:
      - master
    tags:
      - '*'

  workflow_dispatch:

jobs:

  docker:
    name: Build dockers
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
        with:
          install: true
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and push in master
        uses: docker/build-push-action@v4
        if: ${{ github.event.release.tag_name == '' }}
        with:
          push: true
          tags: redislabs/memtier-benchmark:edge
          context: .
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7

      - name: build and push on release
        uses: docker/build-push-action@v4
        if: ${{ github.event.release.tag_name != '' }}
        with:
          push: true
          tags: redislabs/memtier-benchmark:${{ github.event.release.tag_name }}
          context: .
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
